apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
{{- if eq .Values.serviceType "LoadBalancer" }}
  loadBalancerIP: {{ .Values.loadBalancerIP }}
{{- end }}

